- name: Create DB volume (named)
  community.docker.docker_volume:
    name: "{{ db_volume }}"
  vars:
    ansible_python_interpreter: /usr/bin/python3

- name: Run database container (PostgreSQL)
  community.docker.docker_container:
    name: database
    image: "{{ db_image }}"
    pull: yes
    restart_policy: unless-stopped
    env:
      POSTGRES_DB: "{{ db_name }}"
      POSTGRES_USER: "{{ db_user }}"
      POSTGRES_PASSWORD: "{{ db_password }}"
    volumes:
      - "{{ db_volume }}:/var/lib/postgresql/data"
    networks:
      - name: "{{ network_name }}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U {{ db_user }} -d {{ db_name }}"]
      interval: 10s
      timeout: 3s
      retries: 5
  vars:
    ansible_python_interpreter: /usr/bin/python3
