all:
 vars:
   ansible_user: admin
   ansible_ssh_private_key_file: /home/koundjo/Documents/EPF-COURS/devops/Tp2/Devops/id_rsa
 children:
   prod:
     hosts:  brendaaudrey.koundjonguepkap.takima.cloud
