- hosts: all
  become: true
  gather_facts: true

  vars:
    distro_l: "{{ ansible_distribution | lower }}"         
    release_codename: "{{ ansible_distribution_release }}"  
    docker_arch: >-
      {{ 'amd64' if ansible_architecture == 'x86_64'
         else 'arm64' if ansible_architecture in ['aarch64','arm64']
         else ansible_architecture }}

  tasks:
    - name: Update APT cache & base deps
      ansible.builtin.apt:
        update_cache: yes
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present

    - name: Ensure keyrings dir exists
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Docker GPG key
      ansible.builtin.get_url:
        url: "https://download.docker.com/linux/{{ distro_l }}/gpg"
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'
        force: yes

    - name: Add Docker APT repository
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ docker_arch }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/{{ distro_l }} {{ release_codename }} stable"
        filename: docker
        state: present

    - name: Update apt cache after repo add
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Docker Engine
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

      # Install Python3 and pip3
    - name: Install Python3 and pip3
      apt:
       name:
         - python3
         - python3-pip
       state: present


   # Create a virtual environment for Python packages
    - name: Create a virtual environment for Docker SDK
      command: python3 -m venv /opt/docker_venv
      args:
       creates: /opt/docker_venv  # Only runs if this directory doesn’t exist


   # Install Docker SDK for Python in the virtual environment
    - name: Install Docker SDK for Python in virtual environment
      command: /opt/docker_venv/bin/pip install docker


   # Ensure Docker is running
    - name: Make sure Docker is running
      service:
       name: docker
       state: started
      tags: docker