name: CI devops 2025

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]

jobs:
  test-backend:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build and test with Maven
        working-directory: myapp
        run: |
          if [ -f "./mvnw" ]; then
            ./mvnw -B -ntp clean verify
          else
            mvn -B -ntp clean verify
          fi

  build-and-push-docker-image:
    needs: test-backend
    runs-on: ubuntu-24.04
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Vérification des secrets (debug)
      - name: Check DockerHub secrets presence
        run: |
          test -n "${{ secrets.username }}" || (echo " Missing BRENDAAUDREY_USERNAME" && exit 1)
          test -n "${{ secrets.coursdevops}}" || (echo " Missing BRENDAAUDREY (token)" && exit 1)
          echo " Secrets detected"

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.username }}
          password: ${{ secrets.coursdevops}}

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./myapp
          dockerfile: ./myapp/Dockerfile
          push: true
          tags: ${{ secrets.username }}/tp-devops-simple-api-backend:latest

      # Garde ou commente ces deux étapes selon ton proje
      - name: Build and push database image
        uses: docker/build-push-action@v6
        with:
          context: ./db
          dockerfile: ./db/Dockerfile
          push: true
          tags: ${{ secrets.username}}/tp-devops-simple-api-database:latest

      - name: Build and push httpd image
        uses: docker/build-push-action@v6
        with:
          context: ./httpd
          dockerfile: ./httpd/Dockerfile
          push: true
          tags: ${{ secrets.username }}/tp-devops-simple-api-httpd:latest

       # --- DIAGNOSTIC AVANT SONAR ---
      - name: Check Sonar secret presence
        run: |
          test -n "${{ secrets.pwdsonar}}" || (echo " Missing SONAR_TOKEN (Repository secret)" && exit 1)
          echo " SONAR_TOKEN is set."

      - name: Print Java & Maven versions
        run: |
          java -version
          mvn -version

      # --- ANALYSE SONARCLOUD (MODE DEBUG) ---
      - name: SonarCloud analysis (debug)
        working-directory: myapp
        env:
          # Obligatoire : token SonarCloud
          SONAR_TOKEN: ${{ secrets.pwdsonar}}
        run: |
          mvn -B -e -X sonar:sonar \
            -Dsonar.projectKey=BrendaKoundjoDevopsAdministration_myapp \
            -Dsonar.organization=brendakoundjodevopsadministration \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login="$pwdsonar" \
            -Dsonar.sources=src/main \
            -Dsonar.tests=src/test \
            -Dsonar.java.binaries=target/classes
