name: CI devops 2025

on:
  push:
    branches: [dev]
  pull_request:
    branches: [ dev]

jobs:
  test-backend:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build and test with Maven
        working-directory: myapp
        run: |
          if [ -f "./mvnw" ]; then
            ./mvnw -B -ntp clean verify
          else
            mvn -B -ntp clean verify
          fi
