name: CI devops 2025

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  test-backend:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build and test with Maven
        working-directory: myapp
        run: |
          if [ -f "./mvnw" ]; then
            ./mvnw -B -ntp clean verify
          else
            mvn -B -ntp clean verify
          fi

  build-and-push-docker-image:
    needs: test-backend  # s'exécute seulement si les tests passent
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend  # dossier contenant le Dockerfile du backen
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api-backend:latest

      - name: Build and push database image
        uses: docker/build-push-action@v6
        with:
          context: ./database  # dossier contenant le Dockerfile de la base
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api-database:latest

      - name: Build and push httpd image
        uses: docker/build-push-action@v6
        with:
          context: ./httpd  # dossier contenant le Dockerfile httpd
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api-httpd:latest
